apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuberay-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/ray-project/kuberay.git"
    targetRevision: v1.0.0 # Use a specific version for stability
    path: ray-operator/config/crd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
